services:
  - type: web
    name: jogo-reciclagem
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://jogo-reciclagem.onrender.com
